version: '3.7'
networks:
  shipping:
    driver: bridge
services:
  shippingdb:
    image: mysql
    container_name: shippingdb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shippingdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: dbpass
    ports:
      - 3306:3306
    networks:
      - shipping
  shipping-be:
      image: truebu/shipping-be:1.1
      container_name: shipping-be
      restart: unless-stopped
      ports:
        - 8080:8080
      depends_on:
        - shippingdb
      networks:
        - shipping